name: Deploy to SquareCloud

on:
  push:
    branches: [main, master]
    paths:
      - "project/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main, master]
    paths:
      - "project/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "project/package-lock.json"

      - name: Install dependencies
        working-directory: ./project
        run: npm ci

      - name: Build project
        working-directory: ./project
        run: npm run build

      - name: Create deployment package
        run: |
          cd project
          # Remove node_modules to reduce size
          rm -rf node_modules
          # Create zip with only necessary files
          zip -r ../mdbot-deploy-$(date +%Y%m%d-%H%M%S).zip . \
            -x "*.git*" "*.env.local" "*.env.development" \
            "node_modules/*" "src/*" "public/*" \
            "*.md" "*.log" "coverage/*" ".nyc_output/*"
          cd ..

      - name: Deploy to SquareCloud
        env:
          SQUARECLOUD_API_TOKEN: ${{ secrets.SQUARECLOUD_API_TOKEN }}
          SQUARECLOUD_APP_ID: ${{ secrets.SQUARECLOUD_APP_ID }}
        run: |
          # Install SquareCloud CLI
          npm install -g @squarecloud/cli

          # Deploy using CLI
          squarecloud deploy mdbot-deploy-*.zip --app-id $SQUARECLOUD_APP_ID

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deploy realizado com sucesso!"
          else
            echo "❌ Falha no deploy"
          fi
